Fix headless build
paritytech/polkadot-onboard pull request #27
Opened 2023-02-15 21:30 UTC by SaltyCucumber

2023-02-15 22:07 UTC, hamidra requested changes

2023-02-15 22:07 UTC, hamidra commented on packages/core/tsconfig.json
> -    "declaration": true,
Any reason declarations are removed?!

2023-02-15 22:07 UTC, hamidra commented on packages/injected-wallets/src/injectedWallets.ts
> +import { Account, BaseWallet, BaseWalletProvider, WalletMetadata, WalletType } from '@polkadot-onboard/core';
import as type. We would want the lib to have zero dependencies on polkadot.js for tree shaking. These are not needed at runtime so should be only imported as types.

2023-02-15 22:07 UTC, hamidra commented on packages/injected-wallets/tsconfig.json
> -    "declaration": true,
I believe it would be a good practice to export declarations.

2023-02-16 06:33 UTC, hamidra requested changes

2023-02-16 06:33 UTC, hamidra commented on packages/core/package.json
> +    "build:cjs": "tsc --module CommonJS --outDir dist/cjs",
looking at it again I don't think we want to export .cjs here. This lib is only intended to work in browser runtime, so should be imported as esm.

2023-02-16 06:33 UTC, hamidra commented on packages/core/package.json
> -  "type": "module",
This should bot be removed! This lib is intended to be only imported as esm. This is why type:'module' was added in the new version.

2023-02-16 06:36 UTC, hamidra commented
Looking to the headless example, The lib seems to be fine. The issue seems to be with the webpack setup. I don't think this changes are needed. 

It should be set to disable the fullySpecified imports:
https://webpack.js.org/configuration/module/#resolvefullyspecified

I'll send a PR to fix the headless example.

2023-02-16 09:47 UTC, SaltyCucumber commented
Superseded by https://github.com/paritytech/polkadot-onboard/pull/28

2023-02-16 09:47 UTC, closed without merging